package test.twitter

object TwitterHashTagFixture {
  
  def full = """
{
   "statuses":[
      {
         "metadata":{
            "result_type":"recent",
            "iso_language_code":"en"
         },
         "created_at":"Tue Nov 20 20:42:47 +0000 2012",
         "id":270990594216718336,
         "id_str":"270990594216718336",
         "text":"RT @djklipuk: #TheGodfathers #Scala #15\/12\/12 #YoungGuns @nickyblkmkt @fatmandee187 @DefinitionDnB @BioBeatsGang http:\/\/t.co\/FiGtGUhJ",
         "source":"\u003ca href=\"http:\/\/twitter.com\/download\/iphone\" rel=\"nofollow\"\u003eTwitter for iPhone\u003c\/a\u003e",
         "truncated":false,
         "in_reply_to_status_id":null,
         "in_reply_to_status_id_str":null,
         "in_reply_to_user_id":null,
         "in_reply_to_user_id_str":null,
         "in_reply_to_screen_name":null,
         "user":{
            "id":266477516,
            "id_str":"266477516",
            "name":"Nathan Outlaw",
            "screen_name":"no1_outlaw",
            "location":"",
            "description":"DJ \/ PRODUCER",
            "url":null,
            "entities":{
               "description":{
                  "urls":[

                  ]
               }
            },
            "protected":false,
            "followers_count":421,
            "friends_count":331,
            "listed_count":0,
            "created_at":"Tue Mar 15 08:56:20 +0000 2011",
            "favourites_count":6,
            "utc_offset":null,
            "time_zone":null,
            "geo_enabled":true,
            "verified":false,
            "statuses_count":1134,
            "lang":"en",
            "contributors_enabled":false,
            "is_translator":false,
            "profile_background_color":"C0DEED",
            "profile_background_image_url":"http:\/\/a0.twimg.com\/images\/themes\/theme1\/bg.png",
            "profile_background_image_url_https":"https:\/\/si0.twimg.com\/images\/themes\/theme1\/bg.png",
            "profile_background_tile":false,
            "profile_image_url":"http:\/\/a0.twimg.com\/profile_images\/2840789309\/a8a13232a4577484719885f10e921849_normal.jpeg",
            "profile_image_url_https":"https:\/\/si0.twimg.com\/profile_images\/2840789309\/a8a13232a4577484719885f10e921849_normal.jpeg",
            "profile_link_color":"0084B4",
            "profile_sidebar_border_color":"C0DEED",
            "profile_sidebar_fill_color":"DDEEF6",
            "profile_text_color":"333333",
            "profile_use_background_image":true,
            "default_profile":true,
            "default_profile_image":false,
            "following":null,
            "follow_request_sent":null,
            "notifications":null
         },
         "geo":null,
         "coordinates":null,
         "place":null,
         "contributors":null,
         "retweeted_status":{
            "metadata":{
               "result_type":"recent",
               "iso_language_code":"en"
            },
            "created_at":"Tue Nov 20 20:37:34 +0000 2012",
            "id":270989282003525632,
            "id_str":"270989282003525632",
            "text":"#TheGodfathers #Scala #15\/12\/12 #YoungGuns @nickyblkmkt @fatmandee187 @DefinitionDnB @BioBeatsGang http:\/\/t.co\/FiGtGUhJ",
            "source":"\u003ca href=\"http:\/\/instagr.am\" rel=\"nofollow\"\u003eInstagram\u003c\/a\u003e",
            "truncated":false,
            "in_reply_to_status_id":null,
            "in_reply_to_status_id_str":null,
            "in_reply_to_user_id":null,
            "in_reply_to_user_id_str":null,
            "in_reply_to_screen_name":null,
            "user":{
               "id":109543628,
               "id_str":"109543628",
               "name":"DJ Klip",
               "screen_name":"djklipuk",
               "location":"South Coast UK",
               "description":"DJ \/ Producer hailing from South-Coast UK. Biological Beats \/ Eternal Muzic - SoundCloud: http:\/\/t.co\/TXKe7h2h",
               "url":null,
               "entities":{
                  "description":{
                     "urls":[
                        {
                           "url":"http:\/\/t.co\/TXKe7h2h",
                           "expanded_url":"http:\/\/www.soundcloud.com\/klip-outlaw",
                           "display_url":"soundcloud.com\/klip-outlaw",
                           "indices":[
                              90,
                              110
                           ]
                        }
                     ]
                  }
               },
               "protected":false,
               "followers_count":1040,
               "friends_count":442,
               "listed_count":1,
               "created_at":"Fri Jan 29 12:11:52 +0000 2010",
               "favourites_count":4,
               "utc_offset":null,
               "time_zone":null,
               "geo_enabled":false,
               "verified":false,
               "statuses_count":3627,
               "lang":"en",
               "contributors_enabled":false,
               "is_translator":false,
               "profile_background_color":"352726",
               "profile_background_image_url":"http:\/\/a0.twimg.com\/images\/themes\/theme14\/bg.gif",
               "profile_background_image_url_https":"https:\/\/si0.twimg.com\/images\/themes\/theme14\/bg.gif",
               "profile_background_tile":false,
               "profile_image_url":"http:\/\/a0.twimg.com\/profile_images\/2814243054\/3a46e96f7df5afa6b092a185ff797b6c_normal.jpeg",
               "profile_image_url_https":"https:\/\/si0.twimg.com\/profile_images\/2814243054\/3a46e96f7df5afa6b092a185ff797b6c_normal.jpeg",
               "profile_banner_url":"https:\/\/si0.twimg.com\/profile_banners\/109543628\/1349711066",
               "profile_link_color":"D02B55",
               "profile_sidebar_border_color":"829D5E",
               "profile_sidebar_fill_color":"99CC33",
               "profile_text_color":"3E4415",
               "profile_use_background_image":true,
               "default_profile":false,
               "default_profile_image":false,
               "following":null,
               "follow_request_sent":null,
               "notifications":null
            },
            "geo":null,
            "coordinates":null,
            "place":null,
            "contributors":null,
            "retweet_count":3,
            "entities":{
               "hashtags":[
                  {
                     "text":"TheGodfathers",
                     "indices":[
                        0,
                        14
                     ]
                  },
                  {
                     "text":"Scala",
                     "indices":[
                        15,
                        21
                     ]
                  },
                  {
                     "text":"YoungGuns",
                     "indices":[
                        32,
                        42
                     ]
                  }
               ],
               "urls":[
                  {
                     "url":"http:\/\/t.co\/FiGtGUhJ",
                     "expanded_url":"http:\/\/instagr.am\/p\/SQ9FfFMYuT\/",
                     "display_url":"instagr.am\/p\/SQ9FfFMYuT\/",
                     "indices":[
                        99,
                        119
                     ]
                  }
               ],
               "user_mentions":[
                  {
                     "screen_name":"nickyblkmkt",
                     "name":"nicky blackmarket",
                     "id":219029881,
                     "id_str":"219029881",
                     "indices":[
                        43,
                        55
                     ]
                  },
                  {
                     "screen_name":"fatmandee187",
                     "name":"Fatman Dee",
                     "id":281038553,
                     "id_str":"281038553",
                     "indices":[
                        56,
                        69
                     ]
                  },
                  {
                     "screen_name":"DefinitionDnB",
                     "name":"Def:inition Events",
                     "id":31405467,
                     "id_str":"31405467",
                     "indices":[
                        70,
                        84
                     ]
                  },
                  {
                     "screen_name":"BioBeatsGang",
                     "name":"Biological Beats",
                     "id":357402739,
                     "id_str":"357402739",
                     "indices":[
                        85,
                        98
                     ]
                  }
               ]
            },
            "favorited":false,
            "retweeted":false,
            "possibly_sensitive":false
         },
         "retweet_count":3,
         "entities":{
            "hashtags":[
               {
                  "text":"TheGodfathers",
                  "indices":[
                     14,
                     28
                  ]
               },
               {
                  "text":"Scala",
                  "indices":[
                     29,
                     35
                  ]
               },
               {
                  "text":"YoungGuns",
                  "indices":[
                     46,
                     56
                  ]
               }
            ],
            "urls":[
               {
                  "url":"http:\/\/t.co\/FiGtGUhJ",
                  "expanded_url":"http:\/\/instagr.am\/p\/SQ9FfFMYuT\/",
                  "display_url":"instagr.am\/p\/SQ9FfFMYuT\/",
                  "indices":[
                     113,
                     133
                  ]
               }
            ],
            "user_mentions":[
               {
                  "screen_name":"djklipuk",
                  "name":"DJ Klip",
                  "id":109543628,
                  "id_str":"109543628",
                  "indices":[
                     3,
                     12
                  ]
               },
               {
                  "screen_name":"nickyblkmkt",
                  "name":"nicky blackmarket",
                  "id":219029881,
                  "id_str":"219029881",
                  "indices":[
                     57,
                     69
                  ]
               },
               {
                  "screen_name":"fatmandee187",
                  "name":"Fatman Dee",
                  "id":281038553,
                  "id_str":"281038553",
                  "indices":[
                     70,
                     83
                  ]
               },
               {
                  "screen_name":"DefinitionDnB",
                  "name":"Def:inition Events",
                  "id":31405467,
                  "id_str":"31405467",
                  "indices":[
                     84,
                     98
                  ]
               },
               {
                  "screen_name":"BioBeatsGang",
                  "name":"Biological Beats",
                  "id":357402739,
                  "id_str":"357402739",
                  "indices":[
                     99,
                     112
                  ]
               }
            ]
         },
         "favorited":false,
         "retweeted":false,
         "possibly_sensitive":false
      },
      {
         "metadata":{
            "result_type":"recent",
            "iso_language_code":"en"
         },
         "created_at":"Tue Nov 20 20:38:24 +0000 2012",
         "id":270989493442588673,
         "id_str":"270989493442588673",
         "text":"RT @djklipuk: #TheGodfathers #Scala #15\/12\/12 #YoungGuns @nickyblkmkt @fatmandee187 @DefinitionDnB @BioBeatsGang http:\/\/t.co\/FiGtGUhJ",
         "source":"\u003ca href=\"http:\/\/twitter.com\/download\/iphone\" rel=\"nofollow\"\u003eTwitter for iPhone\u003c\/a\u003e",
         "truncated":false,
         "in_reply_to_status_id":null,
         "in_reply_to_status_id_str":null,
         "in_reply_to_user_id":null,
         "in_reply_to_user_id_str":null,
         "in_reply_to_screen_name":null,
         "user":{
            "id":281038553,
            "id_str":"281038553",
            "name":"Fatman Dee",
            "screen_name":"fatmandee187",
            "location":"southside",
            "description":"Dnb mc\/ artist\/ rapper\/ rec label owner part of the New Breed Crew.  FOR BOOKINGS  PLEASE CONTACT URBAN AGENCY AT :  01634 300 046 JON@URBANTAKEOVER.CO.UK",
            "url":"http:\/\/www.facebook.com\/fatamangataman",
            "entities":{
               "url":{
                  "urls":[
                     {
                        "url":"http:\/\/www.facebook.com\/fatamangataman",
                        "expanded_url":null,
                        "indices":[
                           0,
                           38
                        ]
                     }
                  ]
               },
               "description":{
                  "urls":[

                  ]
               }
            },
            "protected":false,
            "followers_count":4134,
            "friends_count":571,
            "listed_count":15,
            "created_at":"Tue Apr 12 14:12:27 +0000 2011",
            "favourites_count":25,
            "utc_offset":null,
            "time_zone":null,
            "geo_enabled":false,
            "verified":false,
            "statuses_count":7145,
            "lang":"en",
            "contributors_enabled":false,
            "is_translator":false,
            "profile_background_color":"C0DEED",
            "profile_background_image_url":"http:\/\/a0.twimg.com\/images\/themes\/theme1\/bg.png",
            "profile_background_image_url_https":"https:\/\/si0.twimg.com\/images\/themes\/theme1\/bg.png",
            "profile_background_tile":false,
            "profile_image_url":"http:\/\/a0.twimg.com\/profile_images\/2771774234\/616b8bfbeb13ae9022e841f0e334f5a6_normal.jpeg",
            "profile_image_url_https":"https:\/\/si0.twimg.com\/profile_images\/2771774234\/616b8bfbeb13ae9022e841f0e334f5a6_normal.jpeg",
            "profile_link_color":"0084B4",
            "profile_sidebar_border_color":"C0DEED",
            "profile_sidebar_fill_color":"DDEEF6",
            "profile_text_color":"333333",
            "profile_use_background_image":true,
            "default_profile":true,
            "default_profile_image":false,
            "following":null,
            "follow_request_sent":null,
            "notifications":null
         },
         "geo":null,
         "coordinates":null,
         "place":null,
         "contributors":null,
         "retweeted_status":{
            "metadata":{
               "result_type":"recent",
               "iso_language_code":"en"
            },
            "created_at":"Tue Nov 20 20:37:34 +0000 2012",
            "id":270989282003525632,
            "id_str":"270989282003525632",
            "text":"#TheGodfathers #Scala #15\/12\/12 #YoungGuns @nickyblkmkt @fatmandee187 @DefinitionDnB @BioBeatsGang http:\/\/t.co\/FiGtGUhJ",
            "source":"\u003ca href=\"http:\/\/instagr.am\" rel=\"nofollow\"\u003eInstagram\u003c\/a\u003e",
            "truncated":false,
            "in_reply_to_status_id":null,
            "in_reply_to_status_id_str":null,
            "in_reply_to_user_id":null,
            "in_reply_to_user_id_str":null,
            "in_reply_to_screen_name":null,
            "user":{
               "id":109543628,
               "id_str":"109543628",
               "name":"DJ Klip",
               "screen_name":"djklipuk",
               "location":"South Coast UK",
               "description":"DJ \/ Producer hailing from South-Coast UK. Biological Beats \/ Eternal Muzic - SoundCloud: http:\/\/t.co\/TXKe7h2h",
               "url":null,
               "entities":{
                  "description":{
                     "urls":[
                        {
                           "url":"http:\/\/t.co\/TXKe7h2h",
                           "expanded_url":"http:\/\/www.soundcloud.com\/klip-outlaw",
                           "display_url":"soundcloud.com\/klip-outlaw",
                           "indices":[
                              90,
                              110
                           ]
                        }
                     ]
                  }
               },
               "protected":false,
               "followers_count":1040,
               "friends_count":442,
               "listed_count":1,
               "created_at":"Fri Jan 29 12:11:52 +0000 2010",
               "favourites_count":4,
               "utc_offset":null,
               "time_zone":null,
               "geo_enabled":false,
               "verified":false,
               "statuses_count":3627,
               "lang":"en",
               "contributors_enabled":false,
               "is_translator":false,
               "profile_background_color":"352726",
               "profile_background_image_url":"http:\/\/a0.twimg.com\/images\/themes\/theme14\/bg.gif",
               "profile_background_image_url_https":"https:\/\/si0.twimg.com\/images\/themes\/theme14\/bg.gif",
               "profile_background_tile":false,
               "profile_image_url":"http:\/\/a0.twimg.com\/profile_images\/2814243054\/3a46e96f7df5afa6b092a185ff797b6c_normal.jpeg",
               "profile_image_url_https":"https:\/\/si0.twimg.com\/profile_images\/2814243054\/3a46e96f7df5afa6b092a185ff797b6c_normal.jpeg",
               "profile_banner_url":"https:\/\/si0.twimg.com\/profile_banners\/109543628\/1349711066",
               "profile_link_color":"D02B55",
               "profile_sidebar_border_color":"829D5E",
               "profile_sidebar_fill_color":"99CC33",
               "profile_text_color":"3E4415",
               "profile_use_background_image":true,
               "default_profile":false,
               "default_profile_image":false,
               "following":null,
               "follow_request_sent":null,
               "notifications":null
            },
            "geo":null,
            "coordinates":null,
            "place":null,
            "contributors":null,
            "retweet_count":3,
            "entities":{
               "hashtags":[
                  {
                     "text":"TheGodfathers",
                     "indices":[
                        0,
                        14
                     ]
                  },
                  {
                     "text":"Scala",
                     "indices":[
                        15,
                        21
                     ]
                  },
                  {
                     "text":"YoungGuns",
                     "indices":[
                        32,
                        42
                     ]
                  }
               ],
               "urls":[
                  {
                     "url":"http:\/\/t.co\/FiGtGUhJ",
                     "expanded_url":"http:\/\/instagr.am\/p\/SQ9FfFMYuT\/",
                     "display_url":"instagr.am\/p\/SQ9FfFMYuT\/",
                     "indices":[
                        99,
                        119
                     ]
                  }
               ],
               "user_mentions":[
                  {
                     "screen_name":"nickyblkmkt",
                     "name":"nicky blackmarket",
                     "id":219029881,
                     "id_str":"219029881",
                     "indices":[
                        43,
                        55
                     ]
                  },
                  {
                     "screen_name":"fatmandee187",
                     "name":"Fatman Dee",
                     "id":281038553,
                     "id_str":"281038553",
                     "indices":[
                        56,
                        69
                     ]
                  },
                  {
                     "screen_name":"DefinitionDnB",
                     "name":"Def:inition Events",
                     "id":31405467,
                     "id_str":"31405467",
                     "indices":[
                        70,
                        84
                     ]
                  },
                  {
                     "screen_name":"BioBeatsGang",
                     "name":"Biological Beats",
                     "id":357402739,
                     "id_str":"357402739",
                     "indices":[
                        85,
                        98
                     ]
                  }
               ]
            },
            "favorited":false,
            "retweeted":false,
            "possibly_sensitive":false
         },
         "retweet_count":3,
         "entities":{
            "hashtags":[
               {
                  "text":"TheGodfathers",
                  "indices":[
                     14,
                     28
                  ]
               },
               {
                  "text":"Scala",
                  "indices":[
                     29,
                     35
                  ]
               },
               {
                  "text":"YoungGuns",
                  "indices":[
                     46,
                     56
                  ]
               }
            ],
            "urls":[
               {
                  "url":"http:\/\/t.co\/FiGtGUhJ",
                  "expanded_url":"http:\/\/instagr.am\/p\/SQ9FfFMYuT\/",
                  "display_url":"instagr.am\/p\/SQ9FfFMYuT\/",
                  "indices":[
                     113,
                     133
                  ]
               }
            ],
            "user_mentions":[
               {
                  "screen_name":"djklipuk",
                  "name":"DJ Klip",
                  "id":109543628,
                  "id_str":"109543628",
                  "indices":[
                     3,
                     12
                  ]
               },
               {
                  "screen_name":"nickyblkmkt",
                  "name":"nicky blackmarket",
                  "id":219029881,
                  "id_str":"219029881",
                  "indices":[
                     57,
                     69
                  ]
               },
               {
                  "screen_name":"fatmandee187",
                  "name":"Fatman Dee",
                  "id":281038553,
                  "id_str":"281038553",
                  "indices":[
                     70,
                     83
                  ]
               },
               {
                  "screen_name":"DefinitionDnB",
                  "name":"Def:inition Events",
                  "id":31405467,
                  "id_str":"31405467",
                  "indices":[
                     84,
                     98
                  ]
               },
               {
                  "screen_name":"BioBeatsGang",
                  "name":"Biological Beats",
                  "id":357402739,
                  "id_str":"357402739",
                  "indices":[
                     99,
                     112
                  ]
               }
            ]
         },
         "favorited":false,
         "retweeted":false,
         "possibly_sensitive":false
      },
      {
         "metadata":{
            "result_type":"recent",
            "iso_language_code":"en"
         },
         "created_at":"Tue Nov 20 20:37:34 +0000 2012",
         "id":270989282003525632,
         "id_str":"270989282003525632",
         "text":"#TheGodfathers #Scala #15\/12\/12 #YoungGuns @nickyblkmkt @fatmandee187 @DefinitionDnB @BioBeatsGang http:\/\/t.co\/FiGtGUhJ",
         "source":"\u003ca href=\"http:\/\/instagr.am\" rel=\"nofollow\"\u003eInstagram\u003c\/a\u003e",
         "truncated":false,
         "in_reply_to_status_id":null,
         "in_reply_to_status_id_str":null,
         "in_reply_to_user_id":null,
         "in_reply_to_user_id_str":null,
         "in_reply_to_screen_name":null,
         "user":{
            "id":109543628,
            "id_str":"109543628",
            "name":"DJ Klip",
            "screen_name":"djklipuk",
            "location":"South Coast UK",
            "description":"DJ \/ Producer hailing from South-Coast UK. Biological Beats \/ Eternal Muzic - SoundCloud: http:\/\/t.co\/TXKe7h2h",
            "url":null,
            "entities":{
               "description":{
                  "urls":[
                     {
                        "url":"http:\/\/t.co\/TXKe7h2h",
                        "expanded_url":"http:\/\/www.soundcloud.com\/klip-outlaw",
                        "display_url":"soundcloud.com\/klip-outlaw",
                        "indices":[
                           90,
                           110
                        ]
                     }
                  ]
               }
            },
            "protected":false,
            "followers_count":1040,
            "friends_count":442,
            "listed_count":1,
            "created_at":"Fri Jan 29 12:11:52 +0000 2010",
            "favourites_count":4,
            "utc_offset":null,
            "time_zone":null,
            "geo_enabled":false,
            "verified":false,
            "statuses_count":3627,
            "lang":"en",
            "contributors_enabled":false,
            "is_translator":false,
            "profile_background_color":"352726",
            "profile_background_image_url":"http:\/\/a0.twimg.com\/images\/themes\/theme14\/bg.gif",
            "profile_background_image_url_https":"https:\/\/si0.twimg.com\/images\/themes\/theme14\/bg.gif",
            "profile_background_tile":false,
            "profile_image_url":"http:\/\/a0.twimg.com\/profile_images\/2814243054\/3a46e96f7df5afa6b092a185ff797b6c_normal.jpeg",
            "profile_image_url_https":"https:\/\/si0.twimg.com\/profile_images\/2814243054\/3a46e96f7df5afa6b092a185ff797b6c_normal.jpeg",
            "profile_banner_url":"https:\/\/si0.twimg.com\/profile_banners\/109543628\/1349711066",
            "profile_link_color":"D02B55",
            "profile_sidebar_border_color":"829D5E",
            "profile_sidebar_fill_color":"99CC33",
            "profile_text_color":"3E4415",
            "profile_use_background_image":true,
            "default_profile":false,
            "default_profile_image":false,
            "following":null,
            "follow_request_sent":null,
            "notifications":null
         },
         "geo":null,
         "coordinates":null,
         "place":null,
         "contributors":null,
         "retweet_count":3,
         "entities":{
            "hashtags":[
               {
                  "text":"TheGodfathers",
                  "indices":[
                     0,
                     14
                  ]
               },
               {
                  "text":"Scala",
                  "indices":[
                     15,
                     21
                  ]
               },
               {
                  "text":"YoungGuns",
                  "indices":[
                     32,
                     42
                  ]
               }
            ],
            "urls":[
               {
                  "url":"http:\/\/t.co\/FiGtGUhJ",
                  "expanded_url":"http:\/\/instagr.am\/p\/SQ9FfFMYuT\/",
                  "display_url":"instagr.am\/p\/SQ9FfFMYuT\/",
                  "indices":[
                     99,
                     119
                  ]
               }
            ],
            "user_mentions":[
               {
                  "screen_name":"nickyblkmkt",
                  "name":"nicky blackmarket",
                  "id":219029881,
                  "id_str":"219029881",
                  "indices":[
                     43,
                     55
                  ]
               },
               {
                  "screen_name":"fatmandee187",
                  "name":"Fatman Dee",
                  "id":281038553,
                  "id_str":"281038553",
                  "indices":[
                     56,
                     69
                  ]
               },
               {
                  "screen_name":"DefinitionDnB",
                  "name":"Def:inition Events",
                  "id":31405467,
                  "id_str":"31405467",
                  "indices":[
                     70,
                     84
                  ]
               },
               {
                  "screen_name":"BioBeatsGang",
                  "name":"Biological Beats",
                  "id":357402739,
                  "id_str":"357402739",
                  "indices":[
                     85,
                     98
                  ]
               }
            ]
         },
         "favorited":false,
         "retweeted":false,
         "possibly_sensitive":false
      },
      {
         "metadata":{
            "result_type":"recent",
            "iso_language_code":"en"
         },
         "created_at":"Tue Nov 20 20:36:39 +0000 2012",
         "id":270989051333591040,
         "id_str":"270989051333591040",
         "text":"#scala #purityring @rlawood getting tickets at its best!! Let's get it started!!  @ Scala http:\/\/t.co\/iTH4sD3S",
         "source":"\u003ca href=\"http:\/\/instagr.am\" rel=\"nofollow\"\u003eInstagram\u003c\/a\u003e",
         "truncated":false,
         "in_reply_to_status_id":null,
         "in_reply_to_status_id_str":null,
         "in_reply_to_user_id":null,
         "in_reply_to_user_id_str":null,
         "in_reply_to_screen_name":null,
         "user":{
            "id":534075847,
            "id_str":"534075847",
            "name":"Nuria Cabrera",
            "screen_name":"cabrera_nuria",
            "location":"London",
            "description":"Past-product designer, graphic designer in the works & just trying right here, right now...",
            "url":null,
            "entities":{
               "description":{
                  "urls":[

                  ]
               }
            },
            "protected":false,
            "followers_count":47,
            "friends_count":243,
            "listed_count":0,
            "created_at":"Fri Mar 23 09:12:33 +0000 2012",
            "favourites_count":3,
            "utc_offset":0,
            "time_zone":"London",
            "geo_enabled":false,
            "verified":false,
            "statuses_count":332,
            "lang":"en",
            "contributors_enabled":false,
            "is_translator":false,
            "profile_background_color":"FCEBB6",
            "profile_background_image_url":"http:\/\/a0.twimg.com\/profile_background_images\/658390563\/x3dfcbd8787a947713c23c62844bbe88.png",
            "profile_background_image_url_https":"https:\/\/si0.twimg.com\/profile_background_images\/658390563\/x3dfcbd8787a947713c23c62844bbe88.png",
            "profile_background_tile":true,
            "profile_image_url":"http:\/\/a0.twimg.com\/profile_images\/1936695066\/CIMG0904copy_normal.jpg",
            "profile_image_url_https":"https:\/\/si0.twimg.com\/profile_images\/1936695066\/CIMG0904copy_normal.jpg",
            "profile_link_color":"CE7834",
            "profile_sidebar_border_color":"F0A830",
            "profile_sidebar_fill_color":"78C0A8",
            "profile_text_color":"5E412F",
            "profile_use_background_image":true,
            "default_profile":false,
            "default_profile_image":false,
            "following":null,
            "follow_request_sent":null,
            "notifications":null
         },
         "geo":null,
         "coordinates":null,
         "place":null,
         "contributors":null,
         "retweet_count":0,
         "entities":{
            "hashtags":[
               {
                  "text":"scala",
                  "indices":[
                     0,
                     6
                  ]
               },
               {
                  "text":"purityring",
                  "indices":[
                     7,
                     18
                  ]
               }
            ],
            "urls":[
               {
                  "url":"http:\/\/t.co\/iTH4sD3S",
                  "expanded_url":"http:\/\/instagr.am\/p\/SQ9O4hENV6\/",
                  "display_url":"instagr.am\/p\/SQ9O4hENV6\/",
                  "indices":[
                     90,
                     110
                  ]
               }
            ],
            "user_mentions":[
               {
                  "screen_name":"RLAWood",
                  "name":"Rebecca Wood",
                  "id":102730336,
                  "id_str":"102730336",
                  "indices":[
                     19,
                     27
                  ]
               }
            ]
         },
         "favorited":false,
         "retweeted":false,
         "possibly_sensitive":false
      },
      {
         "metadata":{
            "result_type":"recent",
            "iso_language_code":"en"
         },
         "created_at":"Tue Nov 20 20:34:12 +0000 2012",
         "id":270988436721238016,
         "id_str":"270988436721238016",
         "text":"RT @gkossakowski: I work on #sbt's incremental compiler to make it smarter about recompiling #scala files. You can track progress here:  ...",
         "source":"\u003ca href=\"http:\/\/twitter.com\/download\/iphone\" rel=\"nofollow\"\u003eTwitter for iPhone\u003c\/a\u003e",
         "truncated":false,
         "in_reply_to_status_id":null,
         "in_reply_to_status_id_str":null,
         "in_reply_to_user_id":null,
         "in_reply_to_user_id_str":null,
         "in_reply_to_screen_name":null,
         "user":{
            "id":289483414,
            "id_str":"289483414",
            "name":"MadridJUG",
            "screen_name":"MadridJUG",
            "location":"Madrid, Spain",
            "description":"El Madrid Java User Group (MadridJUG) es un grupo de desarrolladores cuyo inter\u00e9s es compartir el conocimiento y realizar actividades en torno a Java y la JVM",
            "url":"https:\/\/madridjug.jottit.com\/",
            "entities":{
               "url":{
                  "urls":[
                     {
                        "url":"https:\/\/madridjug.jottit.com\/",
                        "expanded_url":null,
                        "indices":[
                           0,
                           29
                        ]
                     }
                  ]
               },
               "description":{
                  "urls":[

                  ]
               }
            },
            "protected":false,
            "followers_count":223,
            "friends_count":243,
            "listed_count":23,
            "created_at":"Thu Apr 28 18:39:27 +0000 2011",
            "favourites_count":0,
            "utc_offset":3600,
            "time_zone":"Madrid",
            "geo_enabled":false,
            "verified":false,
            "statuses_count":164,
            "lang":"es",
            "contributors_enabled":false,
            "is_translator":false,
            "profile_background_color":"709397",
            "profile_background_image_url":"http:\/\/a0.twimg.com\/images\/themes\/theme6\/bg.gif",
            "profile_background_image_url_https":"https:\/\/si0.twimg.com\/images\/themes\/theme6\/bg.gif",
            "profile_background_tile":false,
            "profile_image_url":"http:\/\/a0.twimg.com\/profile_images\/1361146167\/madridJugDuke_normal.png",
            "profile_image_url_https":"https:\/\/si0.twimg.com\/profile_images\/1361146167\/madridJugDuke_normal.png",
            "profile_link_color":"FF3300",
            "profile_sidebar_border_color":"86A4A6",
            "profile_sidebar_fill_color":"A0C5C7",
            "profile_text_color":"333333",
            "profile_use_background_image":true,
            "default_profile":false,
            "default_profile_image":false,
            "following":null,
            "follow_request_sent":null,
            "notifications":null
         },
         "geo":null,
         "coordinates":null,
         "place":null,
         "contributors":null,
         "retweeted_status":{
            "metadata":{
               "result_type":"recent",
               "iso_language_code":"en"
            },
            "created_at":"Tue Nov 20 19:57:39 +0000 2012",
            "id":270979238545457152,
            "id_str":"270979238545457152",
            "text":"I work on #sbt's incremental compiler to make it smarter about recompiling #scala files. You can track progress here: https:\/\/t.co\/94dJJtta",
            "source":"web",
            "truncated":false,
            "in_reply_to_status_id":null,
            "in_reply_to_status_id_str":null,
            "in_reply_to_user_id":null,
            "in_reply_to_user_id_str":null,
            "in_reply_to_screen_name":null,
            "user":{
               "id":26209148,
               "id_str":"26209148",
               "name":"Grzegorz Kossakowski",
               "screen_name":"gkossakowski",
               "location":"San Francisco",
               "description":"I hack Scala compiler @typesafe. I'm interested in performance, functional programming and large scale. In free time I either read about economy or do sports.",
               "url":null,
               "entities":{
                  "description":{
                     "urls":[

                     ]
                  }
               },
               "protected":false,
               "followers_count":300,
               "friends_count":90,
               "listed_count":14,
               "created_at":"Tue Mar 24 10:03:50 +0000 2009",
               "favourites_count":7,
               "utc_offset":3600,
               "time_zone":"Warsaw",
               "geo_enabled":true,
               "verified":false,
               "statuses_count":539,
               "lang":"en",
               "contributors_enabled":false,
               "is_translator":false,
               "profile_background_color":"C0DEED",
               "profile_background_image_url":"http:\/\/a0.twimg.com\/images\/themes\/theme1\/bg.png",
               "profile_background_image_url_https":"https:\/\/si0.twimg.com\/images\/themes\/theme1\/bg.png",
               "profile_background_tile":false,
               "profile_image_url":"http:\/\/a0.twimg.com\/profile_images\/735848880\/P1000312_normal.jpg",
               "profile_image_url_https":"https:\/\/si0.twimg.com\/profile_images\/735848880\/P1000312_normal.jpg",
               "profile_link_color":"0084B4",
               "profile_sidebar_border_color":"C0DEED",
               "profile_sidebar_fill_color":"DDEEF6",
               "profile_text_color":"333333",
               "profile_use_background_image":true,
               "default_profile":true,
               "default_profile_image":false,
               "following":null,
               "follow_request_sent":null,
               "notifications":null
            },
            "geo":null,
            "coordinates":null,
            "place":null,
            "contributors":null,
            "retweet_count":6,
            "entities":{
               "hashtags":[
                  {
                     "text":"sbt",
                     "indices":[
                        10,
                        14
                     ]
                  },
                  {
                     "text":"scala",
                     "indices":[
                        75,
                        81
                     ]
                  }
               ],
               "urls":[
                  {
                     "url":"https:\/\/t.co\/94dJJtta",
                     "expanded_url":"https:\/\/github.com\/gkossakowski\/xsbt\/commits\/inc",
                     "display_url":"github.com\/gkossakowski\/x\u2026",
                     "indices":[
                        118,
                        139
                     ]
                  }
               ],
               "user_mentions":[

               ]
            },
            "favorited":false,
            "retweeted":false,
            "possibly_sensitive":false
         },
         "retweet_count":6,
         "entities":{
            "hashtags":[
               {
                  "text":"sbt",
                  "indices":[
                     28,
                     32
                  ]
               },
               {
                  "text":"scala",
                  "indices":[
                     93,
                     99
                  ]
               }
            ],
            "urls":[

            ],
            "user_mentions":[
               {
                  "screen_name":"gkossakowski",
                  "name":"Grzegorz Kossakowski",
                  "id":26209148,
                  "id_str":"26209148",
                  "indices":[
                     3,
                     16
                  ]
               }
            ]
         },
         "favorited":false,
         "retweeted":false
      },
      {
         "metadata":{
            "result_type":"recent",
            "iso_language_code":"en"
         },
         "created_at":"Tue Nov 20 20:33:38 +0000 2012",
         "id":270988295062831105,
         "id_str":"270988295062831105",
         "text":"Scala School http:\/\/t.co\/HZEhPJzQ #scala #twitter",
         "source":"\u003ca href=\"http:\/\/www.hootsuite.com\" rel=\"nofollow\"\u003eHootSuite\u003c\/a\u003e",
         "truncated":false,
         "in_reply_to_status_id":null,
         "in_reply_to_status_id_str":null,
         "in_reply_to_user_id":null,
         "in_reply_to_user_id_str":null,
         "in_reply_to_screen_name":null,
         "user":{
            "id":6810142,
            "id_str":"6810142",
            "name":"xavier z\u00e9bier",
            "screen_name":"tixu",
            "location":"Belgium -- Charleroi",
            "description":"",
            "url":null,
            "entities":{
               "description":{
                  "urls":[

                  ]
               }
            },
            "protected":false,
            "followers_count":80,
            "friends_count":454,
            "listed_count":2,
            "created_at":"Thu Jun 14 11:38:31 +0000 2007",
            "favourites_count":107,
            "utc_offset":3600,
            "time_zone":"Brussels",
            "geo_enabled":true,
            "verified":false,
            "statuses_count":1007,
            "lang":"en",
            "contributors_enabled":false,
            "is_translator":false,
            "profile_background_color":"FFFFFF",
            "profile_background_image_url":"http:\/\/a0.twimg.com\/profile_background_images\/310636610\/wallpaper-1227168.jpg",
            "profile_background_image_url_https":"https:\/\/si0.twimg.com\/profile_background_images\/310636610\/wallpaper-1227168.jpg",
            "profile_background_tile":false,
            "profile_image_url":"http:\/\/a0.twimg.com\/profile_images\/1421778960\/avatarhell_kulibali_clock_avs_normal.jpg",
            "profile_image_url_https":"https:\/\/si0.twimg.com\/profile_images\/1421778960\/avatarhell_kulibali_clock_avs_normal.jpg",
            "profile_link_color":"2B6053",
            "profile_sidebar_border_color":"FFFFFF",
            "profile_sidebar_fill_color":"C9E7DF",
            "profile_text_color":"000000",
            "profile_use_background_image":true,
            "default_profile":false,
            "default_profile_image":false,
            "following":null,
            "follow_request_sent":null,
            "notifications":null
         },
         "geo":null,
         "coordinates":null,
         "place":null,
         "contributors":null,
         "retweet_count":1,
         "entities":{
            "hashtags":[
               {
                  "text":"scala",
                  "indices":[
                     34,
                     40
                  ]
               },
               {
                  "text":"twitter",
                  "indices":[
                     41,
                     49
                  ]
               }
            ],
            "urls":[
               {
                  "url":"http:\/\/t.co\/HZEhPJzQ",
                  "expanded_url":"http:\/\/twitter.github.com\/scala_school\/",
                  "display_url":"twitter.github.com\/scala_school\/",
                  "indices":[
                     13,
                     33
                  ]
               }
            ],
            "user_mentions":[

            ]
         },
         "favorited":false,
         "retweeted":false,
         "possibly_sensitive":false
      },
      {
         "metadata":{
            "result_type":"recent",
            "iso_language_code":"en"
         },
         "created_at":"Tue Nov 20 20:33:07 +0000 2012",
         "id":270988163542024192,
         "id_str":"270988163542024192",
         "text":"RT @gkossakowski: I work on #sbt's incremental compiler to make it smarter about recompiling #scala files. You can track progress here:  ...",
         "source":"\u003ca href=\"http:\/\/itunes.apple.com\/us\/app\/twitter\/id409789998?mt=12\" rel=\"nofollow\"\u003eTwitter for Mac\u003c\/a\u003e",
         "truncated":false,
         "in_reply_to_status_id":null,
         "in_reply_to_status_id_str":null,
         "in_reply_to_user_id":null,
         "in_reply_to_user_id_str":null,
         "in_reply_to_screen_name":null,
         "user":{
            "id":18018665,
            "id_str":"18018665",
            "name":"Maur\u00edcio Linhares",
            "screen_name":"mauriciojr",
            "location":"Jo\u00e3o Pessoa, Para\u00edba, Brazil",
            "description":"Programmer, journalist, basketball player and heavy metal maniac",
            "url":"http:\/\/techbot.me\/",
            "entities":{
               "url":{
                  "urls":[
                     {
                        "url":"http:\/\/techbot.me\/",
                        "expanded_url":null,
                        "indices":[
                           0,
                           18
                        ]
                     }
                  ]
               },
               "description":{
                  "urls":[

                  ]
               }
            },
            "protected":false,
            "followers_count":1188,
            "friends_count":251,
            "listed_count":61,
            "created_at":"Wed Dec 10 13:22:16 +0000 2008",
            "favourites_count":12,
            "utc_offset":-10800,
            "time_zone":"Brasilia",
            "geo_enabled":true,
            "verified":false,
            "statuses_count":21561,
            "lang":"en",
            "contributors_enabled":false,
            "is_translator":false,
            "profile_background_color":"8B542B",
            "profile_background_image_url":"http:\/\/a0.twimg.com\/images\/themes\/theme8\/bg.gif",
            "profile_background_image_url_https":"https:\/\/si0.twimg.com\/images\/themes\/theme8\/bg.gif",
            "profile_background_tile":false,
            "profile_image_url":"http:\/\/a0.twimg.com\/profile_images\/1436961531\/954144044421eda622690a48e64e7c92_normal.jpeg",
            "profile_image_url_https":"https:\/\/si0.twimg.com\/profile_images\/1436961531\/954144044421eda622690a48e64e7c92_normal.jpeg",
            "profile_link_color":"9D582E",
            "profile_sidebar_border_color":"D9B17E",
            "profile_sidebar_fill_color":"EADEAA",
            "profile_text_color":"333333",
            "profile_use_background_image":true,
            "default_profile":false,
            "default_profile_image":false,
            "following":null,
            "follow_request_sent":null,
            "notifications":null
         },
         "geo":null,
         "coordinates":null,
         "place":null,
         "contributors":null,
         "retweeted_status":{
            "metadata":{
               "result_type":"recent",
               "iso_language_code":"en"
            },
            "created_at":"Tue Nov 20 19:57:39 +0000 2012",
            "id":270979238545457152,
            "id_str":"270979238545457152",
            "text":"I work on #sbt's incremental compiler to make it smarter about recompiling #scala files. You can track progress here: https:\/\/t.co\/94dJJtta",
            "source":"web",
            "truncated":false,
            "in_reply_to_status_id":null,
            "in_reply_to_status_id_str":null,
            "in_reply_to_user_id":null,
            "in_reply_to_user_id_str":null,
            "in_reply_to_screen_name":null,
            "user":{
               "id":26209148,
               "id_str":"26209148",
               "name":"Grzegorz Kossakowski",
               "screen_name":"gkossakowski",
               "location":"San Francisco",
               "description":"I hack Scala compiler @typesafe. I'm interested in performance, functional programming and large scale. In free time I either read about economy or do sports.",
               "url":null,
               "entities":{
                  "description":{
                     "urls":[

                     ]
                  }
               },
               "protected":false,
               "followers_count":300,
               "friends_count":90,
               "listed_count":14,
               "created_at":"Tue Mar 24 10:03:50 +0000 2009",
               "favourites_count":7,
               "utc_offset":3600,
               "time_zone":"Warsaw",
               "geo_enabled":true,
               "verified":false,
               "statuses_count":539,
               "lang":"en",
               "contributors_enabled":false,
               "is_translator":false,
               "profile_background_color":"C0DEED",
               "profile_background_image_url":"http:\/\/a0.twimg.com\/images\/themes\/theme1\/bg.png",
               "profile_background_image_url_https":"https:\/\/si0.twimg.com\/images\/themes\/theme1\/bg.png",
               "profile_background_tile":false,
               "profile_image_url":"http:\/\/a0.twimg.com\/profile_images\/735848880\/P1000312_normal.jpg",
               "profile_image_url_https":"https:\/\/si0.twimg.com\/profile_images\/735848880\/P1000312_normal.jpg",
               "profile_link_color":"0084B4",
               "profile_sidebar_border_color":"C0DEED",
               "profile_sidebar_fill_color":"DDEEF6",
               "profile_text_color":"333333",
               "profile_use_background_image":true,
               "default_profile":true,
               "default_profile_image":false,
               "following":null,
               "follow_request_sent":null,
               "notifications":null
            },
            "geo":null,
            "coordinates":null,
            "place":null,
            "contributors":null,
            "retweet_count":6,
            "entities":{
               "hashtags":[
                  {
                     "text":"sbt",
                     "indices":[
                        10,
                        14
                     ]
                  },
                  {
                     "text":"scala",
                     "indices":[
                        75,
                        81
                     ]
                  }
               ],
               "urls":[
                  {
                     "url":"https:\/\/t.co\/94dJJtta",
                     "expanded_url":"https:\/\/github.com\/gkossakowski\/xsbt\/commits\/inc",
                     "display_url":"github.com\/gkossakowski\/x\u2026",
                     "indices":[
                        118,
                        139
                     ]
                  }
               ],
               "user_mentions":[

               ]
            },
            "favorited":false,
            "retweeted":false,
            "possibly_sensitive":false
         },
         "retweet_count":6,
         "entities":{
            "hashtags":[
               {
                  "text":"sbt",
                  "indices":[
                     28,
                     32
                  ]
               },
               {
                  "text":"scala",
                  "indices":[
                     93,
                     99
                  ]
               }
            ],
            "urls":[

            ],
            "user_mentions":[
               {
                  "screen_name":"gkossakowski",
                  "name":"Grzegorz Kossakowski",
                  "id":26209148,
                  "id_str":"26209148",
                  "indices":[
                     3,
                     16
                  ]
               }
            ]
         },
         "favorited":false,
         "retweeted":false
      }
   ],
   "search_metadata":{
      "completed_in":0.024,
      "max_id":270990594216718336,
      "max_id_str":"270990594216718336",
      "next_results":"?max_id=270979818080854015&q=%23scala&include_entities=1",
      "query":"%23scala",
      "refresh_url":"?since_id=270990594216718336&q=%23scala&include_entities=1",
      "count":15,
      "since_id":0,
      "since_id_str":"0"
   }
}""";
  
  
  
  
  def short = """
{ 
    "statuses":[
      {
         "metadata":{
            "result_type":"recent",
            "iso_language_code":"en"
         },
         "created_at":"Tue Nov 20 20:42:47 +0000 2012",
         "id":270990594216718336,
         "id_str":"270990594216718336",
         "text":"RT @djklipuk: #TheGodfathers #Scala #15\/12\/12 #YoungGuns @nickyblkmkt @fatmandee187 @DefinitionDnB @BioBeatsGang http:\/\/t.co\/FiGtGUhJ",
         "source":"\u003ca href=\"http:\/\/twitter.com\/download\/iphone\" rel=\"nofollow\"\u003eTwitter for iPhone\u003c\/a\u003e",
         "truncated":false,
         "in_reply_to_status_id":null,
         "in_reply_to_status_id_str":null,
         "in_reply_to_user_id":null,
         "in_reply_to_user_id_str":null,
         "in_reply_to_screen_name":null,
         "user":{
            "id":266477516,
            "id_str":"266477516",
            "name":"Nathan Outlaw",
            "screen_name":"no1_outlaw",
            "location":"",
            "description":"DJ \/ PRODUCER",
            "url":null,
            "entities":{
               "description":{
                  "urls":[

                  ]
               }
            },
            "protected":false,
            "followers_count":421,
            "friends_count":331,
            "listed_count":0,
            "created_at":"Tue Mar 15 08:56:20 +0000 2011",
            "favourites_count":6,
            "utc_offset":null,
            "time_zone":null,
            "geo_enabled":true,
            "verified":false,
            "statuses_count":1134,
            "lang":"en",
            "contributors_enabled":false,
            "is_translator":false,
            "profile_background_color":"C0DEED",
            "profile_background_image_url":"http:\/\/a0.twimg.com\/images\/themes\/theme1\/bg.png",
            "profile_background_image_url_https":"https:\/\/si0.twimg.com\/images\/themes\/theme1\/bg.png",
            "profile_background_tile":false,
            "profile_image_url":"http:\/\/a0.twimg.com\/profile_images\/2840789309\/a8a13232a4577484719885f10e921849_normal.jpeg",
            "profile_image_url_https":"https:\/\/si0.twimg.com\/profile_images\/2840789309\/a8a13232a4577484719885f10e921849_normal.jpeg",
            "profile_link_color":"0084B4",
            "profile_sidebar_border_color":"C0DEED",
            "profile_sidebar_fill_color":"DDEEF6",
            "profile_text_color":"333333",
            "profile_use_background_image":true,
            "default_profile":true,
            "default_profile_image":false,
            "following":null,
            "follow_request_sent":null,
            "notifications":null
         },
         "geo":null,
         "coordinates":null,
         "place":null,
         "contributors":null,
         "retweeted_status":{
            "metadata":{
               "result_type":"recent",
               "iso_language_code":"en"
            },
            "created_at":"Tue Nov 20 20:37:34 +0000 2012",
            "id":270989282003525632,
            "id_str":"270989282003525632",
            "text":"#TheGodfathers #Scala #15\/12\/12 #YoungGuns @nickyblkmkt @fatmandee187 @DefinitionDnB @BioBeatsGang http:\/\/t.co\/FiGtGUhJ",
            "source":"\u003ca href=\"http:\/\/instagr.am\" rel=\"nofollow\"\u003eInstagram\u003c\/a\u003e",
            "truncated":false,
            "in_reply_to_status_id":null,
            "in_reply_to_status_id_str":null,
            "in_reply_to_user_id":null,
            "in_reply_to_user_id_str":null,
            "in_reply_to_screen_name":null,
            "user":{
               "id":109543628,
               "id_str":"109543628",
               "name":"DJ Klip",
               "screen_name":"djklipuk",
               "location":"South Coast UK",
               "description":"DJ \/ Producer hailing from South-Coast UK. Biological Beats \/ Eternal Muzic - SoundCloud: http:\/\/t.co\/TXKe7h2h",
               "url":null,
               "entities":{
                  "description":{
                     "urls":[
                        {
                           "url":"http:\/\/t.co\/TXKe7h2h",
                           "expanded_url":"http:\/\/www.soundcloud.com\/klip-outlaw",
                           "display_url":"soundcloud.com\/klip-outlaw",
                           "indices":[
                              90,
                              110
                           ]
                        }
                     ]
                  }
               },
               "protected":false,
               "followers_count":1040,
               "friends_count":442,
               "listed_count":1,
               "created_at":"Fri Jan 29 12:11:52 +0000 2010",
               "favourites_count":4,
               "utc_offset":null,
               "time_zone":null,
               "geo_enabled":false,
               "verified":false,
               "statuses_count":3627,
               "lang":"en",
               "contributors_enabled":false,
               "is_translator":false,
               "profile_background_color":"352726",
               "profile_background_image_url":"http:\/\/a0.twimg.com\/images\/themes\/theme14\/bg.gif",
               "profile_background_image_url_https":"https:\/\/si0.twimg.com\/images\/themes\/theme14\/bg.gif",
               "profile_background_tile":false,
               "profile_image_url":"http:\/\/a0.twimg.com\/profile_images\/2814243054\/3a46e96f7df5afa6b092a185ff797b6c_normal.jpeg",
               "profile_image_url_https":"https:\/\/si0.twimg.com\/profile_images\/2814243054\/3a46e96f7df5afa6b092a185ff797b6c_normal.jpeg",
               "profile_banner_url":"https:\/\/si0.twimg.com\/profile_banners\/109543628\/1349711066",
               "profile_link_color":"D02B55",
               "profile_sidebar_border_color":"829D5E",
               "profile_sidebar_fill_color":"99CC33",
               "profile_text_color":"3E4415",
               "profile_use_background_image":true,
               "default_profile":false,
               "default_profile_image":false,
               "following":null,
               "follow_request_sent":null,
               "notifications":null
            },
            "geo":null,
            "coordinates":null,
            "place":null,
            "contributors":null,
            "retweet_count":3,
            "entities":{
               "hashtags":[
                  {
                     "text":"TheGodfathers",
                     "indices":[
                        0,
                        14
                     ]
                  },
                  {
                     "text":"Scala",
                     "indices":[
                        15,
                        21
                     ]
                  },
                  {
                     "text":"YoungGuns",
                     "indices":[
                        32,
                        42
                     ]
                  }
               ],
               "urls":[
                  {
                     "url":"http:\/\/t.co\/FiGtGUhJ",
                     "expanded_url":"http:\/\/instagr.am\/p\/SQ9FfFMYuT\/",
                     "display_url":"instagr.am\/p\/SQ9FfFMYuT\/",
                     "indices":[
                        99,
                        119
                     ]
                  }
               ],
               "user_mentions":[
                  {
                     "screen_name":"nickyblkmkt",
                     "name":"nicky blackmarket",
                     "id":219029881,
                     "id_str":"219029881",
                     "indices":[
                        43,
                        55
                     ]
                  },
                  {
                     "screen_name":"fatmandee187",
                     "name":"Fatman Dee",
                     "id":281038553,
                     "id_str":"281038553",
                     "indices":[
                        56,
                        69
                     ]
                  },
                  {
                     "screen_name":"DefinitionDnB",
                     "name":"Def:inition Events",
                     "id":31405467,
                     "id_str":"31405467",
                     "indices":[
                        70,
                        84
                     ]
                  },
                  {
                     "screen_name":"BioBeatsGang",
                     "name":"Biological Beats",
                     "id":357402739,
                     "id_str":"357402739",
                     "indices":[
                        85,
                        98
                     ]
                  }
               ]
            },
            "favorited":false,
            "retweeted":false,
            "possibly_sensitive":false
         },
         "retweet_count":3,
         "entities":{
            "hashtags":[
               {
                  "text":"TheGodfathers",
                  "indices":[
                     14,
                     28
                  ]
               },
               {
                  "text":"Scala",
                  "indices":[
                     29,
                     35
                  ]
               },
               {
                  "text":"YoungGuns",
                  "indices":[
                     46,
                     56
                  ]
               }
            ],
            "urls":[
               {
                  "url":"http:\/\/t.co\/FiGtGUhJ",
                  "expanded_url":"http:\/\/instagr.am\/p\/SQ9FfFMYuT\/",
                  "display_url":"instagr.am\/p\/SQ9FfFMYuT\/",
                  "indices":[
                     113,
                     133
                  ]
               }
            ],
            "user_mentions":[
               {
                  "screen_name":"djklipuk",
                  "name":"DJ Klip",
                  "id":109543628,
                  "id_str":"109543628",
                  "indices":[
                     3,
                     12
                  ]
               },
               {
                  "screen_name":"nickyblkmkt",
                  "name":"nicky blackmarket",
                  "id":219029881,
                  "id_str":"219029881",
                  "indices":[
                     57,
                     69
                  ]
               },
               {
                  "screen_name":"fatmandee187",
                  "name":"Fatman Dee",
                  "id":281038553,
                  "id_str":"281038553",
                  "indices":[
                     70,
                     83
                  ]
               },
               {
                  "screen_name":"DefinitionDnB",
                  "name":"Def:inition Events",
                  "id":31405467,
                  "id_str":"31405467",
                  "indices":[
                     84,
                     98
                  ]
               },
               {
                  "screen_name":"BioBeatsGang",
                  "name":"Biological Beats",
                  "id":357402739,
                  "id_str":"357402739",
                  "indices":[
                     99,
                     112
                  ]
               }
            ]
         },
         "favorited":false,
         "retweeted":false,
         "possibly_sensitive":false
      }
  ]
}
"""

}