package twitter

object TwitterMdFixture {

  val dm = 
    """
  [{
    "id_str":"278930769534152704",
    "created_at":"Wed Dec 12 18:34:12 +0000 2012",
    "recipient_screen_name":"skimbo34",
    "sender_screen_name":"RmManeschi",
    "recipient":{
      "id":854525299,
      "default_profile":false,
      "following":false,
      "profile_background_tile":false,
      "id_str":"854525299",
      "url":"http://t.co/HF9GzusT",
      "profile_sidebar_fill_color":"DDEEF6",
      "profile_image_url":"http://a0.twimg.com/profile_images/2695461507/78279ae92af90ec8c2b3df9cb4d7aaec_normal.png",
      "utc_offset":null,
      "contributors_enabled":false,
      "is_translator":false,
      "time_zone":null,
      "name":"Skimbo",
      "listed_count":0,
      "profile_background_color":"E7E7E7",
      "screen_name":"skimbo34",
      "geo_enabled":false,
      "protected":false,
      "follow_request_sent":false,
      "location":null,
      "entities":{
        "url":{"urls":[{
          "url":"http://t.co/HF9GzusT",
          "indices":[0,20],
          "display_url":"skimbo.studio-dev.fr",
          "expanded_url":"http://skimbo.studio-dev.fr/"}]},
        "description":{"urls":[]}
      },
      "profile_background_image_url":"http://a0.twimg.com/profile_background_images/728139847/e8d52b2cba6aa3040e9c605c39977dac.png",
      "friends_count":9,
      "profile_link_color":"BD0D1C",
      "statuses_count":14,
      "notifications":false,
      "default_profile_image":false,
      "favourites_count":1,
      "lang":"fr",
      "profile_background_image_url_https":"https://si0.twimg.com/profile_background_images/728139847/e8d52b2cba6aa3040e9c605c39977dac.png",
      "profile_use_background_image":true,
      "verified":false,
      "profile_text_color":"333333",
      "profile_image_url_https":"https://si0.twimg.com/profile_images/2695461507/78279ae92af90ec8c2b3df9cb4d7aaec_normal.png",
      "followers_count":7,
      "profile_banner_url":"https://si0.twimg.com/profile_banners/854525299/1354540674",
      "profile_sidebar_border_color":"000000",
      "description":"Froggies Team is proud to present Skimbo, a social networks mashup.\r\n#scala #akka and #playframework in action\r\nApp submited for @typesafe developper contest",
      "created_at":"Sun Sep 30 10:58:57 +0000 2012"},
    "recipient_id":854525299,
    "entities":{
      "urls":[],
      "hashtags":[],
      "user_mentions":[]},
    "sender":{
      "id":297864800,
      "default_profile":false,
      "following":true,
      "profile_background_tile":true,
      "id_str":"297864800",
      "url":"http://lydiman.net",
      "profile_sidebar_fill_color":"efefef",
      "profile_image_url":"http://a0.twimg.com/profile_images/1351663536/Logo_KC_Flex_normal.png",
      "utc_offset":3600,
      "contributors_enabled":false,
      "is_translator":false,
      "time_zone":"Paris",
      "name":"Romain Maneschi",
      "listed_count":3,
      "profile_background_color":"131516",
      "screen_name":"RmManeschi",
      "geo_enabled":false,
      "protected":false,
      "follow_request_sent":false, 
      "location":"Montpellier",
      "entities":{
        "url":{"urls":[
          {"url":"http://lydiman.net","indices":[0,18],"display_url":null,"expanded_url":null}]},
        "description":{"urls":[]}},
      "profile_background_image_url":"http://a0.twimg.com/images/themes/theme14/bg.gif",
      "friends_count":94,
      "profile_link_color":"009999",
      "statuses_count":191,
      "notifications":false,
      "default_profile_image":false,
      "favourites_count":5,
      "lang":"fr",
      "profile_background_image_url_https":"https://si0.twimg.com/images/themes/theme14/bg.gif",
      "profile_use_background_image":true,
      "verified":false,
      "profile_text_color":"333333",
      "profile_image_url_https":"https://si0.twimg.com/profile_images/1351663536/Logo_KC_Flex_normal.png",
      "followers_count":38,
      "profile_sidebar_border_color":"eeeeee",
      "description":"Développeur web, en quête perpétuelle de nouvelles choses... ",
      "created_at":"Fri May 13 07:47:41 +0000 2011"},
    "text":"test message privé",
    "id":278930769534152704,
    "sender_id":297864800}]
    """
  
}