#!/bin/bash

# debug
# set -x

#loads VERSION, DEPS_PARAMS, ID, LOG_FILE, PLAY_COMMAND="${OPENSHIFT_DATA_DIR}play-${VERSION}/play"
. ${OPENSHIFT_REPO_DIR}.openshift/action_hooks/load_config

if [[ ! $? -eq 0 ]]; then
	exit $?
fi

PLAY_PATH="play-$VERSION/"

# use tmp file just in case it hangs up
PLAY_ARCH="${OPENSHIFT_DATA_DIR}play-$VERSION.zip"

cd "$OPENSHIFT_DATA_DIR"

if [[ -d $PLAY_PATH ]]; then
	echo "Play $VERSION already installed at `pwd`/$PLAY_PATH"
else

	echo "Installing play $VERSION"

	if [[ -f $PLAY_ARCH ]]; then
		rm $PLAY_ARCH
	fi

	PLAY_URL="http://downloads.typesafe.com/play/$VERSION/play-$VERSION.zip"
	curl -o $PLAY_ARCH $PLAY_URL

	if [[ ! -f $PLAY_ARCH ]]; then
		echo "Error downloading play $VERSION from $PLAY_URL"
		exit 1
	fi

	unzip "$PLAY_ARCH"
	rm $PLAY_ARCH

	PLAY_FULL_PATH="${OPENSHIFT_DATA_DIR}${PLAY_PATH}"

	if [[ ! -d $PLAY_FULL_PATH ]]; then
		echo "Error installing play $VERSION to $PLAY_FULL_PATH"
		exit 1
	fi
fi

exit 0
