#!/bin/bash

echo "##### Deploy to openshift strating #####"

PATH_PLAY=""
PATH_PROJECT=""
OPENSHIFT_REPO="openshift"
OPENSHIFT_BRANCH="master"

echo "##### cd $PATH_PROJECT #####"
cd $PATH_PROJECT

echo "##### Running ${PATH_PLAY}/play clean compile stage #####"
bash -c "${PATH_PLAY}/play clean compile stage"

echo "##### Add target to git #####"
git add -f target/*
echo "##### Commit to git #####"
git commit -m "deploy start on openshift"
echo "##### Push to $OPENSHIFT_REPO / $OPENSHIFT_BRANCH #####"
git push $OPENSHIFT_REPO $OPENSHIFT_BRANCH
echo "##### Delete target to git #####"
git rm -r -f target
echo "##### Discard last commit with new commit to git #####"
git commit -m "deploy end on openshift"
